all: fir_offline  fir_online  iir_offline  iir_online  iirbig_offline  iirbig_online  wire
 
wire: wire.c
	cc -o wire wire.c

fir_offline: fir_offline.c
	cc -o fir_offline fir_offline.c

fir_online: fir_online.c
	cc -o fir_online fir_online.c

iir_offline: iir_offline.c
	cc -o iir_offline iir_offline.c

iirbig_offline: iirbig_offline.c
	cc -o iirbig_offline iirbig_offline.c

iirbig_online: iirbig_online.c
	cc -o iirbig_online iirbig_online.c
